### ISSUE TITLE
Pytorch version

### ISSUE THREAD

**Issue by ytongbai** [mbanani/pytorch-clickhere-cnn#3]
Hi, which version of PyTorch did you use to train this model? When I used the 0.4.1 version, it came up with this error: 
"RuntimeError: Expected object of type torch.cuda.FloatTensor but found type torch.cuda.LongTensor for argument #4 'mat1'".
Is it because I use the wrong version or anything else? Could you please help me with that?
Thanks a lot!

**Comment by mbanani** [comment]
My apologies again for the late response -- I was unaware of issues on this (and my guess is that it's probably way overdue now). 

The problem seems to be due to tensor type mismatch (not PyTorch version). If you let me know which line it is, I could provide more clear feedback. My apologies again.
